version: 2.1
jobs:
  build:
     docker:
       - image: golang:latest
     working_directory: /go/src/github.com/michelesantosl1/aulaa-ci
     steps:
       - checkout
       - run: 
           name: Run tests
           command: go test -v
       
